# Generated by Django 4.1.5 on 2024-06-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('all_mileage', models.FloatField(default=0.0, help_text='km.m')),
                ('busy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('login', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_time', models.DateTimeField(auto_now_add=True)),
                ('return_time', models.DateTimeField(blank=True)),
                ('travel_start_point', models.TextField(blank=True)),
                ('travel_target_point', models.TextField(blank=True)),
                ('travel_mileage', models.FloatField(default=0.0, help_text='km.m')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activitylog.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitylog.user')),
            ],
        ),
    ]
