# Generated by Django 5.0.7 on 2024-07-18 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='get_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
