# Generated by Django 4.1.5 on 2024-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
