# Generated by Django 4.1.5 on 2024-07-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0002_alter_activitylog_return_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='activitylog.user'),
            preserve_default=False,
        ),
    ]
